### PR TITLE
Y7S4 downloads as Y7S2 + wrong plaza

### PR DESCRIPTION
**Pull request by prettyleaf**
Have only changed dir name to correct one and changed plaza (it only works with Y8SX)

Other strings were edited cuz github wants so: "We’ve detected the file encoding as ISO-8859-1. When you commit changes we will transcode it to UTF-8."

### CODE REVIEW

**Comment by SlejmUr** [comment]
Thanks for the fix,
Sadly the manifest will not work because of #1.
Will do a big update if y8s2 events release.
(The manifest probably are in the database from other AIO-CSharp file if you can edit it for that version I be glad

**Comment by SlejmUr** [comment]
Y7S4_SolarRaid -> 6 December 2022 (AKA Release date)
Y7S4_SnowBrawl -> 7 February 2023 (AKA Last/First Event date)

(I suggest using the feb7 manifest)
359551	1819898955518120444
377239	991763536720350080
377238	5107849703917033235
377237	4466027729495813039

**Comment by prettyleaf** [comment]
> Thanks for the fix, Sadly the manifest will not work because of #1. Will do a big update if y8s2 events release. (The manifest probably are in the database from other AIO-CSharp file if you can edit it for that version I be glad

btw events released. waiting for "big update" B)

**Comment by SlejmUr** [comment]
Yup using that as a Y8S1-2-3? Idk

**Comment by SlejmUr** [comment]
Check the new commit!
I fixed (or should) all issues

**Pull request closed without merging**
